import { describe, expect, it } from 'vitest';
import { getActionDescriptionText, getActionTitleText } from './actionLocalization';
import { createInitialPlayState } from './timers';
import type { ActionResolutionContext, ContentBundle, GameAction } from './types';

// A faithful-enough stand-in for the real app's t(): consults a locale
// dictionary by key first, only falling back to the caller-supplied fallback
// (which is itself sometimes a pre-rendered generic string, per
// getActionTitleText's "specific key wins over generic template" pattern).
const makeTranslator = (locales: Record<string, string>) => (
  key: string,
  fallbackOrParams?: string | Record<string, string | number>,
  params?: Record<string, string | number>,
) => {
  const fallback = typeof fallbackOrParams === 'string' ? fallbackOrParams : key;
  const interpolation = typeof fallbackOrParams === 'object' ? fallbackOrParams : params;
  const template = locales[key] ?? fallback;
  return interpolation
    ? template.replace(/\{([^}]+)\}/g, (match, name) => String(interpolation[name] ?? match))
    : template;
};

const baseLocales = {
  'location.forest.title': 'Forest',
  'action.travel.title': 'Travel to {location} ({duration}s)',
  'action.travel.description': 'Go to {location}.',
};

const travelAction: GameAction = {
  id: 'adjacent-start-to-forest',
  locationId: 'start',
  role: 'travel',
  rewards: [],
  results: [{ kind: 'relocate', locationId: 'forest' }],
};

const bundle: ContentBundle = {
  manifest: { schemaVersion: 1, id: 'test', version: '1', author: 'test', locales: ['en'], files: [] },
  locations: [
    { id: 'start', position: { x: 0, y: 0 }, starting: true },
    { id: 'forest', position: { x: 1, y: 0 } },
  ],
  entities: [],
  actions: [travelAction],
  skills: [],
  stats: [],
  items: [],
  flags: [],
  resourceDefinitions: [],
  effects: [],
  interactionTypes: [],
  enemies: [],
  locales: { en: baseLocales },
};

const context: ActionResolutionContext = {
  actions: bundle.actions,
  skills: bundle.skills,
  stats: bundle.stats,
  locations: bundle.locations,
  entities: bundle.entities,
  items: bundle.items,
  flags: bundle.flags,
  resourceDefinitions: bundle.resourceDefinitions,
  effects: bundle.effects,
  interactionTypes: bundle.interactionTypes,
  enemies: bundle.enemies,
  manifest: bundle.manifest,
};

describe('autogenerated travel action titles', () => {
  it('shows the destination and duration when no module-authored title exists', () => {
    const state = createInitialPlayState('test', 'start');
    const t = makeTranslator(baseLocales);
    expect(getActionTitleText(travelAction, bundle, t, state, context)).toBe('Travel to Forest (1s)');
  });

  it('still lets an explicit module-authored title win over the generic one', () => {
    const t = makeTranslator({ ...baseLocales, 'action.adjacent-start-to-forest.title': 'Sprint to the forest' });
    const state = createInitialPlayState('test', 'start');
    expect(getActionTitleText(travelAction, bundle, t, state, context)).toBe('Sprint to the forest');
  });

  it('description falls back to the generic "Go to X" text, independent of duration', () => {
    const t = makeTranslator(baseLocales);
    expect(getActionDescriptionText(travelAction, bundle, t)).toBe('Go to Forest.');
  });
});
