import { areActionRequirementsMet, isActionVisible } from './conditions';
import { getCharacterStatValue } from './characterStats';
import { resolveManifestUiSettings } from './universeSettings';
import type { ActionResolutionContext, ActionResult, ContentBundle, GameAction, LocationNode, Position, UniversePlayState } from './types';

export type AvailableTravelEdge = {
  action: GameAction;
  id: string;
  source: string;
  target: string;
  travelTimeSeconds: number;
};

export type TravelPathResult =
  | { status: 'found'; edges: AvailableTravelEdge[]; totalSeconds: number }
  | { status: 'not-found' }
  | { status: 'too-far' };

export const MOVEMENT_SPEED_STAT_ID = 'movement-speed';
const DEFAULT_MOVEMENT_SPEED = 60;

export const travelEdgeId = (action: Pick<GameAction, 'id'>) => `travel:${action.id}`;

// A "pure" travel action costs and rewards nothing and does nothing but move
// the player (any number of `chat` results alongside the `relocate` are
// fine — narration doesn't cost anything). This covers both location-level
// `adjacent:` edges (`role: 'travel'`, but that's incidental — nothing here
// requires it) and free-standing entity actions that are just a ladder,
// tunnel, or portal (a `say:` + `relocate:` action with no other tags) — the
// two are structurally the same thing, just declared in different DSL
// sections, so this doesn't distinguish them.
export const getPureTravelDestination = (action: GameAction): string | null => {
  const results = action.results ?? [];
  const relocateResults = results.filter((result): result is Extract<ActionResult, { kind: 'relocate' }> => result.kind === 'relocate');
  const otherResults = results.filter((result) => result.kind !== 'relocate' && result.kind !== 'chat');

  if (
    action.rewards.length > 0 ||
    relocateResults.length !== 1 ||
    otherResults.length > 0 ||
    action.experience?.length ||
    action.enemyId ||
    action.interactionTypeId
  ) {
    return null;
  }

  return relocateResults[0].locationId;
};

export const isPureTravelAction = (action: GameAction) => getPureTravelDestination(action) !== null;

const locationZ = (location: Pick<LocationNode, 'position'>) => location.position.z ?? 0;

const gridDistance = (from: Position, to: Position) => {
  const dx = to.x - from.x;
  const dy = to.y - from.y;
  return Math.sqrt(dx * dx + dy * dy);
};

const computeTravelSeconds = (
  state: UniversePlayState,
  context: ActionResolutionContext,
  from: Position,
  to: Position,
) => {
  const settings = resolveManifestUiSettings(context.manifest);
  const movementSpeed = getCharacterStatValue(
    state,
    context.stats ?? [],
    MOVEMENT_SPEED_STAT_ID,
    context.skills,
    context.items ?? [],
    context.manifest?.experienceCurve,
    context.statModifiers,
  ) || DEFAULT_MOVEMENT_SPEED;
  const distanceUnits = gridDistance(from, to) * settings.distanceBetweenAdjacentTiles;
  return distanceUnits / (movementSpeed / 60);
};

export const getAvailableTravelEdgesForNode = (
  state: UniversePlayState,
  context: ActionResolutionContext,
  locationId: string,
): AvailableTravelEdge[] => {
  const nodeState = {
    ...state,
    currentLocationId: locationId,
  };
  const sourceLocation = context.locations?.find((location) => location.id === locationId);
  if (!sourceLocation) return [];

  const buildEdge = (targetLocation: LocationNode, action: GameAction): AvailableTravelEdge => ({
    action,
    id: travelEdgeId(action),
    source: locationId,
    target: targetLocation.id,
    travelTimeSeconds: computeTravelSeconds(nodeState, context, sourceLocation.position, targetLocation.position),
  });

  // Available here means either a location-level edge (an `adjacent:`-
  // authored action) or a free-standing entity action belonging to one of
  // this location's own entities (a ladder, tunnel, portal — declared right
  // where the player interacts with it, not on the location itself).
  const entityIdsHere = new Set(sourceLocation.entities ?? []);

  return context.actions.flatMap((action) => {
    const availableHere = action.locationId === locationId || (action.entityId !== undefined && entityIdsHere.has(action.entityId));
    if (!availableHere) return [];
    const destination = getPureTravelDestination(action);
    if (!destination) return [];
    if (!isActionVisible(nodeState, action, context) || !areActionRequirementsMet(nodeState, action, context)) {
      return [];
    }
    const targetLocation = context.locations?.find((location) => location.id === destination);
    if (!targetLocation) return [];
    return [buildEdge(targetLocation, action)];
  });
};

// For display purposes only (e.g. labeling an autogenerated "Travel to X
// (Ns)" button) — reuses the same per-node edge computation the map/
// pathfinding use, so the number shown always matches what actually governs
// travel time, even though a travel action started directly from the action
// list (rather than the map) completes instantly (see
// `validation.travelDurationUnused`).
export const getTravelActionDurationSeconds = (
  action: GameAction,
  state: UniversePlayState,
  context: ActionResolutionContext,
): number | null => {
  const sourceLocationId = action.locationId
    ?? context.locations?.find((location) => action.entityId !== undefined && (location.entities ?? []).includes(action.entityId))?.id;
  if (!sourceLocationId) return null;
  const edge = getAvailableTravelEdgesForNode(state, context, sourceLocationId).find((candidate) => candidate.action.id === action.id);
  return edge ? edge.travelTimeSeconds : null;
};

// `viewZ` lets the map show a layer other than the player's current one (a
// z-height selector) — defaults to the current location's z when omitted, so
// existing callers see no change. Fog-of-war still applies uniformly: only
// already-discovered locations/edges ever show, on any layer.
export const getVisibleTravelGraph = (
  bundle: ContentBundle,
  playState: UniversePlayState,
  context: ActionResolutionContext,
  viewZ?: number,
) => {
  const explored = new Set(playState.discoveredLocationIds);
  const visibleLocationIds = new Set<string>(explored);
  const edges = playState.discoveredLocationIds.flatMap((locationId) => {
    const fromExploredNode = getAvailableTravelEdgesForNode(playState, context, locationId);
    for (const edge of fromExploredNode) {
      visibleLocationIds.add(edge.target);
    }
    return fromExploredNode;
  });

  if (playState.activeTravel) {
    for (const locationId of playState.activeTravel.pathLocationIds) {
      visibleLocationIds.add(locationId);
    }
  }

  const targetZ = viewZ ?? locationZ(bundle.locations.find((location) => location.id === playState.currentLocationId) ?? { position: { x: 0, y: 0 } });
  const locations = bundle.locations.filter((location) => visibleLocationIds.has(location.id) && locationZ(location) === targetZ);
  const visibleOnLayer = new Set(locations.map((location) => location.id));

  return {
    locations,
    edges: edges.filter((edge) => visibleOnLayer.has(edge.source) && visibleOnLayer.has(edge.target)),
  };
};

export const findTravelPath = (
  state: UniversePlayState,
  context: ActionResolutionContext,
  targetLocationId: string,
): TravelPathResult => {
  if (state.currentLocationId === targetLocationId) {
    return { status: 'found', edges: [], totalSeconds: 0 };
  }

  const settings = resolveManifestUiSettings(context.manifest);
  const maxSeconds = settings.travelPathMaxSeconds;
  const maxNodes = settings.travelPathMaxNodes;
  const explored = new Set(state.discoveredLocationIds);
  const frontier: Array<{ locationId: string; edges: AvailableTravelEdge[]; totalSeconds: number }> = [
    { locationId: state.currentLocationId, edges: [], totalSeconds: 0 },
  ];
  const bestSeconds = new Map<string, number>([[state.currentLocationId, 0]]);
  let hitLimit = false;

  while (frontier.length > 0) {
    frontier.sort((left, right) => left.totalSeconds - right.totalSeconds);
    const current = frontier.shift()!;

    if (current.locationId === targetLocationId) {
      return { status: 'found', edges: current.edges, totalSeconds: current.totalSeconds };
    }
    if (current.edges.length >= maxNodes) {
      hitLimit = true;
      continue;
    }

    for (const edge of getAvailableTravelEdgesForNode(state, context, current.locationId)) {
      const canTraverse = edge.target === targetLocationId || explored.has(edge.target);
      if (!canTraverse) {
        continue;
      }

      const totalSeconds = current.totalSeconds + edge.travelTimeSeconds;
      if (totalSeconds > maxSeconds) {
        hitLimit = true;
        continue;
      }

      const best = bestSeconds.get(edge.target);
      if (best !== undefined && best <= totalSeconds) {
        continue;
      }

      bestSeconds.set(edge.target, totalSeconds);
      frontier.push({
        locationId: edge.target,
        edges: [...current.edges, edge],
        totalSeconds,
      });
    }
  }

  return hitLimit ? { status: 'too-far' } : { status: 'not-found' };
};

export type CardinalDirection = 'n' | 's' | 'e' | 'w' | 'ne' | 'nw' | 'se' | 'sw';

// Screen convention: -y is north (up), +y is south (down), matching how the
// map already lays locations out for ReactFlow (which renders y growing
// downward).
export const cardinalDirectionOffsets: Record<CardinalDirection, { dx: number; dy: number }> = {
  n: { dx: 0, dy: -1 },
  s: { dx: 0, dy: 1 },
  e: { dx: 1, dy: 0 },
  w: { dx: -1, dy: 0 },
  ne: { dx: 1, dy: -1 },
  nw: { dx: -1, dy: -1 },
  se: { dx: 1, dy: 1 },
  sw: { dx: -1, dy: 1 },
};

export const getLocationInDirection = (
  bundle: Pick<ContentBundle, 'locations'>,
  currentLocationId: string,
  direction: CardinalDirection,
): LocationNode | null => {
  const current = bundle.locations.find((location) => location.id === currentLocationId);
  if (!current) return null;
  const offset = cardinalDirectionOffsets[direction];
  const z = locationZ(current);
  return bundle.locations.find((candidate) =>
    candidate.id !== current.id
    && locationZ(candidate) === z
    && candidate.position.x === current.position.x + offset.dx
    && candidate.position.y === current.position.y + offset.dy) ?? null;
};
