import type { EngineKey } from '../content/locale';

export const LABELS = {
  map: 'engine.shell.map',
  edit: 'engine.shell.edit',
  home: 'engine.shell.home',
  settings: 'engine.shell.settings',
  stats: 'engine.shell.stats',
  skills: 'engine.shell.skills',
  equipment: 'engine.shell.equipment',
  inventory: 'engine.shell.inventory',
  command: 'engine.shell.command',
  recentre: 'engine.shell.recentre',
  socket: 'engine.shell.socket',
  allocate: 'engine.shell.allocate',
  insert: 'engine.shell.insert',
  feed: 'engine.shell.feed',
  empty: 'engine.shell.empty',
  experience: 'engine.shell.experience',
  'to-next': 'engine.shell.to-next',
  'an-hour': 'engine.shell.an-hour',
  'until-next': 'engine.shell.until-next',
  run: 'engine.shell.run',
  level: 'engine.shell.level',
  points: 'engine.shell.points',
  spent: 'engine.shell.spent',
  ready: 'engine.shell.ready',
  locked: 'engine.shell.locked',
  dead: 'engine.shell.dead',
  free: 'engine.shell.free',
  position: 'engine.shell.node.position',
  slot: 'engine.shell.node.slot',
  local: 'engine.shell.local',
  global: 'engine.shell.global',
  'every-kind': 'engine.shell.every-kind',
  section: 'engine.shell.section',
  grammar: 'engine.shell.grammar',
  unread: 'engine.shell.unread',
  'step-in': 'engine.shell.step-in',
  'step-out': 'engine.shell.step-out',
  new: 'engine.shell.new',
  search: 'engine.shell.search',
  'search-hint': 'engine.shell.search-hint',
  'command-line': 'engine.shell.command-line',
  stage: 'engine.shell.stage',
  unstage: 'engine.shell.unstage',
  copy: 'engine.shell.copy',
  place: 'engine.shell.place',
  link: 'engine.shell.link',
  dev: 'engine.shell.dev',
  speed: 'engine.shell.speed',
  clear: 'engine.shell.clear',
  reopen: 'engine.shell.reopen',
} as const satisfies Record<string, EngineKey>;

export type LabelId = keyof typeof LABELS;
